#!/usr/bin/env bash
uv python install --default
uv python install 3.10 3.11 3.12 3.13
uv tool install pre-commit --with pre-commit-uv --force-reinstall
uv tool install tox --with tox-uv
pre-commit install --install-hooks -t pre-commit -t commit-msg -t post-commit -t pre-push
